// login
export const LOGIN_CHANGE_USERNAME = 'login/CHANGE_USERNAME'
export const LOGIN_CHANGE_PASSWORD = 'login/CHANGE_PASSWORD'
export const LOGIN_CHANGE_RESULT = 'login/CHANGE_RESULT'

// blog - post
export const BLOG_CHANGE_TAB = 'blog/CHANGE_TAB'
export const BLOG_RECEIVE_POSTS = 'blog/RECEIVE_POSTS'
export const BLOG_SELECT_POST = 'blog/SELECT_POST'
export const BLOG_DESELECT_POST = 'blog/DESELECT_POST'
export const BLOG_CHANGE_SEARCH_KEY = 'blog/CHANGE_SEARCH_KEY'
export const BLOG_CHANGE_POST_TITLE = 'blog/CHANGE_POST_TITLE'
export const BLOG_CHANGE_POST_CONTENT = 'blog/CHANGE_POST_CONTENT'
export const BLOG_CHANGE_POST_STATUS = 'blog/CHANGE_POST_STATUS'
export const BLOG_CHANGE_POST_COVER = 'blog/CHANGE_POST_COVER'
export const BLOG_CHANGE_POST_TAGS = 'blog/CHANGE_POST_TAGS'
export const BLOG_CHANGE_POST = 'blog/CHANGE_POST'
export const BLOG_CHANGE_IMAGE_SELECTOR_MODAL_STATUS = 'blog/CHANGE_IMAGE_SELECTOR_MODAL_STATUS'
